### ISSUE TITLE
manager v1

### ISSUE THREAD

**Issue by LouisonGitzinger** [Rapacademix/redbull#21]
## Script manager v1

Create a simple web interface allowing us to remotely manage our scripts on a distant machine.

### TODO

- [ ] Auto pull VPS repo on master commit

- [ ] Create DB `script` table: 
- name
- type (one_shot, updater)
- added
- description
- help

- [ ] Create `script_run` table
- script_id
- logs
- state (FAILED, STOPPED, RUNNING)
- added

- [ ] Create index page displaying script list

- [ ] Create one page per script to manage each one
- Run/stop button
- display logs
- display general information

- [ ] implement task manager with Redis Queue
